### ISSUE TITLE
AMR-WB IO mode - thoughts

### ISSUE THREAD

**Issue by mtryfoss** [traud/asterisk-evs#3]
Hello!

As stated in the README, AMR-WB IO is not supported. However, I wonder a bit how this would work in Asterisk. I've not found much details regarding how clients behave.

Will this primarily be a change in res_format_attr_evs.c or the codec module itself?
For example, will the EVS decoder produce AMR-WB frames instead of slin?

**Comment by traud** [comment]
I love to share my knowledge. However, these questions are more like a consulting job. You have my E-mail address.
